"""initial_schema

Revision ID: a015e0a72188
Revises:
Create Date: 2026-08-30 15:10:46.193940

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a015e0a72188"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estate_structure_templates",
        sa.Column("template_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=True,
            comment="residential | commercial | mixed | gated_community | estate | apartment",
        ),
        sa.Column(
            "levels",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Array of level definitions:\n        [\n          {"level": 1, "label": "Street", "type": "text", "required": true},\n          {"level": 2, "label": "House Number", "type": "alphanumeric", "required": true}\n        ]\n        Types: text, numeric, alphanumeric, select (with options array)\n        ',
        ),
        sa.Column(
            "address_format",
            sa.String(length=200),
            nullable=True,
            comment="Display format template: '{Street}, House {House Number}'",
        ),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_estate_structure_templates_category"),
        "estate_structure_templates",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estate_structure_templates_id"), "estate_structure_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_estate_structure_templates_template_id"),
        "estate_structure_templates",
        ["template_id"],
        unique=True,
    )
    op.create_table(
        "firms",
        sa.Column("firm_code", sa.String(length=10), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("cac_number", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column("primary_contact_name", sa.String(length=100), nullable=True),
        sa.Column("primary_contact_phone", sa.String(length=20), nullable=True),
        sa.Column("primary_contact_email", sa.String(length=100), nullable=True),
        sa.Column("nin_verified", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_firms_firm_code"), "firms", ["firm_code"], unique=True)
    op.create_index(op.f("ix_firms_id"), "firms", ["id"], unique=False)
    op.create_table(
        "otps",
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("otp_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "REGISTRATION",
                "LOGIN",
                "PIN_RESET",
                "PHONE_CHANGE",
                "ADD_MEMBER",
                "ESTATE_REGISTRATION",
                name="otppurpose",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otps_id"), "otps", ["id"], unique=False)
    op.create_index(op.f("ix_otps_phone_number"), "otps", ["phone_number"], unique=False)
    op.create_table(
        "payment_ledger",
        sa.Column("estate_id", sa.String(), nullable=False),
        sa.Column("bill_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("paystack_reference", sa.String(length=100), nullable=False),
        sa.Column("paystack_transaction_id", sa.Integer(), nullable=True),
        sa.Column("gross_amount_kobo", sa.Integer(), nullable=False),
        sa.Column("paystack_fee_kobo", sa.Integer(), nullable=False),
        sa.Column("platform_fee_kobo", sa.Integer(), nullable=False),
        sa.Column("estate_settlement_kobo", sa.Integer(), nullable=False),
        sa.Column("fee_bearer", sa.String(length=20), nullable=True),
        sa.Column("settlement_status", sa.String(length=20), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_channel", sa.String(length=20), nullable=True),
        sa.Column("card_type", sa.String(length=20), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled", sa.Boolean(), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_ledger_estate_id"), "payment_ledger", ["estate_id"], unique=False
    )
    op.create_index(op.f("ix_payment_ledger_id"), "payment_ledger", ["id"], unique=False)
    op.create_index(
        op.f("ix_payment_ledger_paystack_reference"),
        "payment_ledger",
        ["paystack_reference"],
        unique=True,
    )
    op.create_table(
        "platform_users",
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "role",
            sa.String(length=30),
            nullable=True,
            comment="platform_admin | platform_super_admin | support",
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Granular permissions: {"manage_estates": true, "manage_billing": true}',
        ),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("last_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_platform_users_email"), "platform_users", ["email"], unique=True)
    op.create_index(op.f("ix_platform_users_id"), "platform_users", ["id"], unique=False)
    op.create_table(
        "residents",
        sa.Column("house_number", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column(
            "nin", sa.String(length=20), nullable=True, comment="National Identification Number"
        ),
        sa.Column(
            "house_entity_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structure-specific data: block, street, floor, unit, etc.",
        ),
        sa.Column(
            "is_registered",
            sa.Boolean(),
            nullable=True,
            comment="True when this resident has created an app account",
        ),
        sa.Column(
            "registered_user_id",
            sa.String(),
            nullable=True,
            comment="user.id of the app account linked to this pre-loaded record",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_residents_house_number"), "residents", ["house_number"], unique=False)
    op.create_index(op.f("ix_residents_id"), "residents", ["id"], unique=False)
    op.create_index(op.f("ix_residents_phone_number"), "residents", ["phone_number"], unique=False)
    op.create_table(
        "staff",
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_id"), "staff", ["id"], unique=False)
    op.create_index(op.f("ix_staff_phone_number"), "staff", ["phone_number"], unique=False)
    op.create_table(
        "status_history",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_history_entity_id"), "status_history", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_status_history_entity_type"), "status_history", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_status_history_id"), "status_history", ["id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("entity_type", sa.String(length=20), nullable=False, comment="estate | firm"),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column(
            "plan",
            sa.String(length=50),
            nullable=False,
            comment="trial | basic | standard | premium | enterprise",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=True,
            comment="trial | active | past_due | expired | cancelled",
        ),
        sa.Column(
            "funding_source",
            sa.String(length=20),
            nullable=False,
            comment="resident_billing (default) | direct — direct means the estate/firm itself is charged instead of splitting the cost across residents via a Bill",
        ),
        sa.Column(
            "current_cycle_bill_id",
            sa.String(),
            nullable=True,
            comment="Bill.id (tenant schema, bill_type='platform_subscription') generated for the active billing cycle",
        ),
        sa.Column("current_cycle_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "current_cycle_due_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Mirrors the cycle Bill's due_date — when residents must have finished paying this cycle",
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paystack_subscription_code", sa.String(length=100), nullable=True),
        sa.Column("paystack_customer_code", sa.String(length=100), nullable=True),
        sa.Column("paystack_plan_code", sa.String(length=100), nullable=True),
        sa.Column("amount_ngn", sa.Float(), nullable=True),
        sa.Column(
            "billing_cycle",
            sa.String(length=20),
            nullable=True,
            comment="monthly | quarterly | yearly",
        ),
        sa.Column(
            "max_houses",
            sa.Integer(),
            nullable=True,
            comment="Max houses allowed on this plan (null = unlimited)",
        ),
        sa.Column("max_staff", sa.Integer(), nullable=True, comment="Max staff accounts allowed"),
        sa.Column(
            "features",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Enabled features: {"chat": true, "vote": true, "expenses": false}',
        ),
        sa.Column("auto_renew", sa.Boolean(), nullable=True),
        sa.Column("renewal_reminder_sent", sa.Boolean(), nullable=True),
        sa.Column("current_cycle_total_expected", sa.Integer(), nullable=True),
        sa.Column("current_cycle_total_paid", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_current_cycle_bill_id"),
        "subscriptions",
        ["current_cycle_bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_entity_id"), "subscriptions", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_entity_type"), "subscriptions", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_table(
        "system_health_checks",
        sa.Column(
            "overall_status",
            sa.String(length=30),
            nullable=False,
            comment="operational | degraded | partial_outage | major_outage",
        ),
        sa.Column(
            "overall_label",
            sa.String(length=100),
            nullable=False,
            comment="Human label: 'All Systems Operational'",
        ),
        sa.Column(
            "services",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Array of {name, status, response_time_ms, description}",
        ),
        sa.Column("uptime_seconds", sa.Float(), nullable=False),
        sa.Column("has_incident", sa.Boolean(), nullable=False),
        sa.Column("incident_services", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_health_incident_created",
        "system_health_checks",
        ["has_incident", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_health_checks_has_incident"),
        "system_health_checks",
        ["has_incident"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_health_checks_id"), "system_health_checks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_health_checks_overall_status"),
        "system_health_checks",
        ["overall_status"],
        unique=False,
    )
    op.create_table(
        "estates",
        sa.Column("estate_code", sa.String(length=10), nullable=False),
        sa.Column("schema_name", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("local_government", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("gps_latitude", sa.Float(), nullable=True),
        sa.Column("gps_longitude", sa.Float(), nullable=True),
        sa.Column("estate_logo_url", sa.String(length=500), nullable=True),
        sa.Column("has_structure", sa.Boolean(), nullable=True),
        sa.Column(
            "structure_template_id",
            sa.String(length=50),
            nullable=True,
            comment="ID from estate_structure_templates table, or 'custom'",
        ),
        sa.Column(
            "structure_definition",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Full structure definition (levels array) — either from template or custom",
        ),
        sa.Column(
            "is_custom_structure",
            sa.Boolean(),
            nullable=True,
            comment="True if user requested a custom structure not in preloaded templates",
        ),
        sa.Column("house_count_tier", sa.String(length=20), nullable=True),
        sa.Column("actual_house_count", sa.Integer(), nullable=True),
        sa.Column(
            "registered_by", sa.String(), nullable=True, comment="platform_user.id who registered"
        ),
        sa.Column(
            "management_type",
            sa.String(length=20),
            nullable=True,
            comment="community | firm — who manages this estate",
        ),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("onboarding_step", sa.String(length=30), nullable=True),
        sa.Column(
            "subscription_id", sa.String(), nullable=True, comment="Connected subscription record"
        ),
        sa.Column("settlement_bank_code", sa.String(length=10), nullable=True),
        sa.Column("settlement_account_number", sa.String(length=20), nullable=True),
        sa.Column("settlement_account_name", sa.String(length=200), nullable=True),
        sa.Column("paystack_subaccount_code", sa.String(length=50), nullable=True),
        sa.Column("paystack_subaccount_id", sa.Integer(), nullable=True),
        sa.Column("platform_fee_percentage", sa.Float(), nullable=True),
        sa.Column("fee_bearer", sa.String(length=20), nullable=True),
        sa.Column("stakeholder_email_sent", sa.Boolean(), nullable=True),
        sa.Column("center_panel_credentials_sent", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schema_name"),
    )
    op.create_index(op.f("ix_estates_estate_code"), "estates", ["estate_code"], unique=True)
    op.create_index(op.f("ix_estates_id"), "estates", ["id"], unique=False)
    op.create_index(op.f("ix_estates_status"), "estates", ["status"], unique=False)
    op.create_table(
        "firm_admins",
        sa.Column("firm_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "designated_estate_id",
            sa.String(),
            nullable=True,
            comment="Estate this firm admin is designated to manage",
        ),
        sa.Column(
            "is_primary_contact",
            sa.Boolean(),
            nullable=True,
            comment="Primary contact for resident approvals",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_firm_admins_designated_estate_id"),
        "firm_admins",
        ["designated_estate_id"],
        unique=False,
    )
    op.create_index(op.f("ix_firm_admins_email"), "firm_admins", ["email"], unique=True)
    op.create_index(op.f("ix_firm_admins_firm_id"), "firm_admins", ["firm_id"], unique=False)
    op.create_index(op.f("ix_firm_admins_id"), "firm_admins", ["id"], unique=False)
    op.create_table(
        "platform_audit_log",
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column(
            "actor_type",
            sa.String(length=20),
            nullable=False,
            comment="platform_admin | platform_super_admin | system",
        ),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=True,
            comment="estate | subscription | stakeholder | platform_user",
        ),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("estate_id", sa.String(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_audit_log_actor_id"), "platform_audit_log", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_audit_log_estate_id"), "platform_audit_log", ["estate_id"], unique=False
    )
    op.create_index(op.f("ix_platform_audit_log_id"), "platform_audit_log", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("resident_id", sa.String(), nullable=True),
        sa.Column("estate_id", sa.String(), nullable=True),
        sa.Column("house_number", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("profile_image", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "RESIDENT",
                "STAFF",
                "SECURITY",
                "ADMIN_SECRETARY",
                "SECRETARY",
                "TREASURER",
                "ADMIN",
                "SUPER_ADMIN",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pin_hash", sa.String(length=255), nullable=True),
        sa.Column("facial_capture_url", sa.String(length=500), nullable=True),
        sa.Column("nin", sa.String(length=20), nullable=True),
        sa.Column(
            "verification_tier",
            sa.Enum(
                "PRE_VERIFIED",
                "ADMIN_APPROVED",
                "VOUCHED",
                "SELF_REGISTERED",
                name="verificationtier",
            ),
            nullable=False,
        ),
        sa.Column(
            "vouch_code",
            sa.String(length=20),
            nullable=True,
            comment="Unique code for sharing vouch links via WhatsApp/socials",
        ),
        sa.Column(
            "registration_source",
            sa.String(length=30),
            nullable=True,
            comment="estate_id | vouch | self | admin_invite | csv_import",
        ),
        sa.Column("primary_holder_id", sa.String(), nullable=True),
        sa.Column(
            "connection_type",
            sa.Enum("FAMILY", "TENANT", "DOMESTIC_STAFF", "CARETAKER", name="connectiontype"),
            nullable=True,
        ),
        sa.Column("slot_number", sa.Integer(), nullable=True),
        sa.Column("pin_attempts", sa.Integer(), nullable=True),
        sa.Column("pin_locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["primary_holder_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_estate_id"), "users", ["estate_id"], unique=False)
    op.create_index(op.f("ix_users_house_number"), "users", ["house_number"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)
    op.create_index(op.f("ix_users_resident_id"), "users", ["resident_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(
        op.f("ix_users_verification_tier"), "users", ["verification_tier"], unique=False
    )
    op.create_index(op.f("ix_users_vouch_code"), "users", ["vouch_code"], unique=True)
    op.create_table(
        "activity_logs",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column(
            "activity_type",
            sa.String(length=50),
            nullable=False,
            comment="Category string (not PG enum) for extensibility",
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="Brief verb: Created, Updated, Deleted, Approved ...",
        ),
        sa.Column("description", sa.Text(), nullable=False, comment="Human-readable description"),
        sa.Column(
            "target_type",
            sa.String(length=50),
            nullable=True,
            comment="Model name: Bill, User, VisitorCode, Expense ...",
        ),
        sa.Column("target_id", sa.String(), nullable=True, comment="UUID of affected record"),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Extra context: old/new values, amounts, references",
        ),
        sa.Column(
            "severity", sa.String(length=10), nullable=False, comment="info | warning | critical"
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_actlog_severity", "activity_logs", ["severity", "created_at"], unique=False
    )
    op.create_index(
        "idx_actlog_target", "activity_logs", ["target_type", "target_id"], unique=False
    )
    op.create_index(
        "idx_actlog_type_created", "activity_logs", ["activity_type", "created_at"], unique=False
    )
    op.create_index(
        "idx_actlog_user_created", "activity_logs", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_activity_type"), "activity_logs", ["activity_type"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_activity_logs_target_id"), "activity_logs", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_target_type"), "activity_logs", ["target_type"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)
    op.create_table(
        "bills",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "CLOSED", "CANCELLED", name="billstatus"),
            nullable=True,
        ),
        sa.Column(
            "bill_type",
            sa.String(length=50),
            nullable=True,
            comment="security_levy | electricity | ... | platform_subscription",
        ),
        sa.Column("total_expected", sa.Integer(), nullable=True),
        sa.Column("total_paid", sa.Integer(), nullable=True),
        sa.Column(
            "is_platform_bill",
            sa.Boolean(),
            nullable=True,
            comment="True for bill_type='platform_subscription' — payments on this bill settle 100% to the platform, bypassing the estate's Paystack subaccount split entirely",
        ),
        sa.Column(
            "source_type",
            sa.String(length=50),
            nullable=True,
            comment="What generated this bill, e.g. 'subscription' | 'admin' | 'expense'",
        ),
        sa.Column(
            "source_id",
            sa.String(),
            nullable=True,
            comment="ID of the source record, e.g. Subscription.id when source_type='subscription' (public schema — no cross-schema FK)",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bills_id"), "bills", ["id"], unique=False)
    op.create_index(op.f("ix_bills_is_platform_bill"), "bills", ["is_platform_bill"], unique=False)
    op.create_index(op.f("ix_bills_source_id"), "bills", ["source_id"], unique=False)
    op.create_index(op.f("ix_bills_status"), "bills", ["status"], unique=False)
    op.create_index(op.f("ix_bills_user_id"), "bills", ["user_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=True),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=True),
        sa.Column("media_url", sa.String(length=500), nullable=True),
        sa.Column("reply_to_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["chat_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_channel"), "chat_messages", ["channel"], unique=False)
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(op.f("ix_chat_messages_user_id"), "chat_messages", ["user_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="expensestatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("UNPAID", "PARTIALLY_PAID", "PAID", name="expensepaymentstatus"),
            nullable=True,
        ),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("receipt_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    op.create_index(op.f("ix_expenses_status"), "expenses", ["status"], unique=False)
    op.create_table(
        "house_entities",
        sa.Column("estate_id", sa.String(), nullable=False),
        sa.Column(
            "address_components",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Key-value pairs following structure: {"Block": "A", "Floor": "3", "Flat": "12"}',
        ),
        sa.Column(
            "formatted_address",
            sa.String(length=200),
            nullable=False,
            comment="Human-readable: 'Block A, Floor 3, Flat 12'",
        ),
        sa.Column(
            "house_number",
            sa.String(length=50),
            nullable=True,
            comment="Short reference like 'A-3-12' — generated from components",
        ),
        sa.Column("is_occupied", sa.Boolean(), nullable=True),
        sa.Column("occupant_name", sa.String(length=100), nullable=True),
        sa.Column("occupant_phone", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["estate_id"],
            ["estates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_house_entities_estate_id"), "house_entities", ["estate_id"], unique=False
    )
    op.create_index(
        op.f("ix_house_entities_formatted_address"),
        "house_entities",
        ["formatted_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_house_entities_house_number"), "house_entities", ["house_number"], unique=False
    )
    op.create_index(op.f("ix_house_entities_id"), "house_entities", ["id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "SENT", "PAID", "OVERDUE", "CANCELLED", name="invoicestatus"),
            nullable=True,
        ),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=True)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(op.f("ix_invoices_user_id"), "invoices", ["user_id"], unique=False)
    op.create_table(
        "member_permissions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("granted_by", sa.String(), nullable=False),
        sa.Column("can_pay_bills", sa.Boolean(), nullable=True),
        sa.Column("can_create_visitor_code", sa.Boolean(), nullable=True),
        sa.Column("can_view_bills", sa.Boolean(), nullable=True),
        sa.Column("can_community_chat", sa.Boolean(), nullable=True),
        sa.Column("can_report_issues", sa.Boolean(), nullable=True),
        sa.Column("can_view_expenses", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_member_permissions_id"), "member_permissions", ["id"], unique=False)
    op.create_index(
        op.f("ix_member_permissions_user_id"), "member_permissions", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "BILL",
                "PAYMENT",
                "VISITOR",
                "ANNOUNCEMENT",
                "VERIFICATION",
                "SYSTEM",
                name="notificationtype",
            ),
            nullable=True,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "panic_alerts",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "reason",
            sa.String(length=100),
            nullable=False,
            comment="Pre-filled reason: fire, intrusion, medical, theft, other",
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="active | acknowledged | resolved | false_alarm | cancelled",
        ),
        sa.Column("gps_latitude", sa.Float(), nullable=True),
        sa.Column("gps_longitude", sa.Float(), nullable=True),
        sa.Column("house_number", sa.String(length=50), nullable=True),
        sa.Column("acknowledged_by", sa.String(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "trigger_method",
            sa.String(length=20),
            nullable=True,
            comment="button | gesture | voice — how alert was triggered",
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_panic_alerts_id"), "panic_alerts", ["id"], unique=False)
    op.create_index(op.f("ix_panic_alerts_reason"), "panic_alerts", ["reason"], unique=False)
    op.create_index(op.f("ix_panic_alerts_status"), "panic_alerts", ["status"], unique=False)
    op.create_index(op.f("ix_panic_alerts_user_id"), "panic_alerts", ["user_id"], unique=False)
    op.create_table(
        "stakeholders",
        sa.Column("estate_id", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("nin", sa.String(length=20), nullable=True),
        sa.Column(
            "role_title",
            sa.String(length=50),
            nullable=True,
            comment="chairman | secretary | treasurer | stakeholder | firm_rep",
        ),
        sa.Column(
            "is_primary", sa.Boolean(), nullable=True, comment="Primary contact for approvals"
        ),
        sa.Column(
            "has_panel_access", sa.Boolean(), nullable=True, comment="Can access estate admin panel"
        ),
        sa.Column("panel_password_hash", sa.String(length=255), nullable=True),
        sa.Column("last_login", sa.String(), nullable=True),
        sa.Column("nin_verified", sa.Boolean(), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["estate_id"],
            ["estates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stakeholders_estate_id"), "stakeholders", ["estate_id"], unique=False)
    op.create_index(op.f("ix_stakeholders_id"), "stakeholders", ["id"], unique=False)
    op.create_table(
        "support_tickets",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_support_tickets_id"), "support_tickets", ["id"], unique=False)
    op.create_index(op.f("ix_support_tickets_status"), "support_tickets", ["status"], unique=False)
    op.create_index(
        op.f("ix_support_tickets_user_id"), "support_tickets", ["user_id"], unique=False
    )
    op.create_table(
        "verification_requests",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("requested_tier", sa.String(length=20), nullable=False),
        sa.Column(
            "method",
            sa.String(length=30),
            nullable=False,
            comment="vouch | admin_review | csv_match | nin_verify",
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "EXPIRED", name="verificationstatus"),
            nullable=True,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "vouch_code",
            sa.String(length=20),
            nullable=True,
            comment="Shareable code for vouch links (Figma: share via WhatsApp etc.)",
        ),
        sa.Column(
            "vouch_link_url",
            sa.String(length=500),
            nullable=True,
            comment="Deep link URL: rezzident.app/vouch/{vouch_code}",
        ),
        sa.Column(
            "min_vouches_required",
            sa.Integer(),
            nullable=True,
            comment="Figma says 'at least 2' neighbors",
        ),
        sa.Column("vouches_received", sa.Integer(), nullable=True),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.String(), nullable=True),
        sa.Column(
            "facial_capture_url",
            sa.String(length=500),
            nullable=True,
            comment="Facial capture submitted during verification",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_requests_id"), "verification_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_requests_status"), "verification_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_verification_requests_user_id"), "verification_requests", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_requests_vouch_code"),
        "verification_requests",
        ["vouch_code"],
        unique=True,
    )
    op.create_table(
        "visitor_codes",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("visitor_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("visitor_image", sa.String(length=500), nullable=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("time_of_visit", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_for_visit", sa.Text(), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_visitor_codes_code"), "visitor_codes", ["code"], unique=True)
    op.create_index(op.f("ix_visitor_codes_id"), "visitor_codes", ["id"], unique=False)
    op.create_index(op.f("ix_visitor_codes_user_id"), "visitor_codes", ["user_id"], unique=False)
    op.create_table(
        "votes",
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "vote_type",
            sa.String(length=20),
            nullable=False,
            comment="poll | election | levy_approval | resolution",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="draft | active | closed | cancelled",
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Array of option objects: [{"id": "a", "label": "Yes"}, ...]',
        ),
        sa.Column("allow_multiple_choices", sa.Boolean(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column(
            "min_verification_tier",
            sa.Integer(),
            nullable=True,
            comment="Minimum verification tier to vote (Figma: only Tier 2 users)",
        ),
        sa.Column("total_votes", sa.Integer(), nullable=True),
        sa.Column(
            "results_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Cached results: {"option_id": count, ...}',
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_votes_id"), "votes", ["id"], unique=False)
    op.create_index(op.f("ix_votes_status"), "votes", ["status"], unique=False)
    op.create_index(op.f("ix_votes_vote_type"), "votes", ["vote_type"], unique=False)
    op.create_table(
        "expense_approvals",
        sa.Column("expense_id", sa.String(), nullable=False),
        sa.Column("approver_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="approvalstatus"),
            nullable=True,
        ),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_approvals_expense_id"), "expense_approvals", ["expense_id"], unique=False
    )
    op.create_index(op.f("ix_expense_approvals_id"), "expense_approvals", ["id"], unique=False)
    op.create_table(
        "expense_items",
        sa.Column("expense_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_items_expense_id"), "expense_items", ["expense_id"], unique=False
    )
    op.create_index(op.f("ix_expense_items_id"), "expense_items", ["id"], unique=False)
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_items_id"), "invoice_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_invoice_items_invoice_id"), "invoice_items", ["invoice_id"], unique=False
    )
    op.create_table(
        "invoice_payments",
        sa.Column("invoice_id", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_payments_id"), "invoice_payments", ["id"], unique=False)
    op.create_index(
        op.f("ix_invoice_payments_invoice_id"), "invoice_payments", ["invoice_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("bill_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("paystack_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=True,
        ),
        sa.Column(
            "channel",
            sa.Enum("CARD", "BANK_TRANSFER", "USSD", "CASH", name="paymentchannel"),
            nullable=True,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index(op.f("ix_payments_bill_id"), "payments", ["bill_id"], unique=False)
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "resident_bills",
        sa.Column("bill_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("house_number", sa.String(length=50), nullable=True),
        sa.Column("amount_due", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PARTIALLY_PAID", "PAID", "OVERDUE", "WAIVED", name="residentbillstatus"
            ),
            nullable=True,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resident_bills_bill_id"), "resident_bills", ["bill_id"], unique=False)
    op.create_index(op.f("ix_resident_bills_id"), "resident_bills", ["id"], unique=False)
    op.create_index(op.f("ix_resident_bills_status"), "resident_bills", ["status"], unique=False)
    op.create_index(op.f("ix_resident_bills_user_id"), "resident_bills", ["user_id"], unique=False)
    op.create_table(
        "verification_vouches",
        sa.Column("verification_request_id", sa.String(), nullable=False),
        sa.Column("voucher_user_id", sa.String(), nullable=False),
        sa.Column("voucher_house_number", sa.String(length=50), nullable=True),
        sa.Column("voucher_full_name", sa.String(length=100), nullable=True),
        sa.Column("voucher_phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("vouched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "vouch_method",
            sa.String(length=20),
            nullable=True,
            comment="link | code | in_app — how the vouch was submitted",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["verification_request_id"],
            ["verification_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voucher_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_vouches_id"), "verification_vouches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_vouches_verification_request_id"),
        "verification_vouches",
        ["verification_request_id"],
        unique=False,
    )
    op.create_table(
        "visitors",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("visitor_code_id", sa.String(), nullable=True),
        sa.Column("visitor_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("visitor_image", sa.String(length=500), nullable=True),
        sa.Column("purpose", sa.String(length=100), nullable=True),
        sa.Column("reason_for_visit", sa.Text(), nullable=True),
        sa.Column("house_number", sa.String(length=50), nullable=True),
        sa.Column("time_of_visit", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_in_by", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_code_id"],
            ["visitor_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_visitors_id"), "visitors", ["id"], unique=False)
    op.create_index(op.f("ix_visitors_user_id"), "visitors", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_visitors_visitor_code_id"), "visitors", ["visitor_code_id"], unique=False
    )
    op.create_table(
        "vote_ballots",
        sa.Column("vote_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "selected_options",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Array of selected option IDs: ["a", "c"]',
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vote_id"],
            ["votes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vote_ballots_id"), "vote_ballots", ["id"], unique=False)
    op.create_index(op.f("ix_vote_ballots_user_id"), "vote_ballots", ["user_id"], unique=False)
    op.create_index(op.f("ix_vote_ballots_vote_id"), "vote_ballots", ["vote_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vote_ballots_vote_id"), table_name="vote_ballots")
    op.drop_index(op.f("ix_vote_ballots_user_id"), table_name="vote_ballots")
    op.drop_index(op.f("ix_vote_ballots_id"), table_name="vote_ballots")
    op.drop_table("vote_ballots")
    op.drop_index(op.f("ix_visitors_visitor_code_id"), table_name="visitors")
    op.drop_index(op.f("ix_visitors_user_id"), table_name="visitors")
    op.drop_index(op.f("ix_visitors_id"), table_name="visitors")
    op.drop_table("visitors")
    op.drop_index(
        op.f("ix_verification_vouches_verification_request_id"), table_name="verification_vouches"
    )
    op.drop_index(op.f("ix_verification_vouches_id"), table_name="verification_vouches")
    op.drop_table("verification_vouches")
    op.drop_index(op.f("ix_resident_bills_user_id"), table_name="resident_bills")
    op.drop_index(op.f("ix_resident_bills_status"), table_name="resident_bills")
    op.drop_index(op.f("ix_resident_bills_id"), table_name="resident_bills")
    op.drop_index(op.f("ix_resident_bills_bill_id"), table_name="resident_bills")
    op.drop_table("resident_bills")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_bill_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_invoice_payments_invoice_id"), table_name="invoice_payments")
    op.drop_index(op.f("ix_invoice_payments_id"), table_name="invoice_payments")
    op.drop_table("invoice_payments")
    op.drop_index(op.f("ix_invoice_items_invoice_id"), table_name="invoice_items")
    op.drop_index(op.f("ix_invoice_items_id"), table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(op.f("ix_expense_items_id"), table_name="expense_items")
    op.drop_index(op.f("ix_expense_items_expense_id"), table_name="expense_items")
    op.drop_table("expense_items")
    op.drop_index(op.f("ix_expense_approvals_id"), table_name="expense_approvals")
    op.drop_index(op.f("ix_expense_approvals_expense_id"), table_name="expense_approvals")
    op.drop_table("expense_approvals")
    op.drop_index(op.f("ix_votes_vote_type"), table_name="votes")
    op.drop_index(op.f("ix_votes_status"), table_name="votes")
    op.drop_index(op.f("ix_votes_id"), table_name="votes")
    op.drop_table("votes")
    op.drop_index(op.f("ix_visitor_codes_user_id"), table_name="visitor_codes")
    op.drop_index(op.f("ix_visitor_codes_id"), table_name="visitor_codes")
    op.drop_index(op.f("ix_visitor_codes_code"), table_name="visitor_codes")
    op.drop_table("visitor_codes")
    op.drop_index(op.f("ix_verification_requests_vouch_code"), table_name="verification_requests")
    op.drop_index(op.f("ix_verification_requests_user_id"), table_name="verification_requests")
    op.drop_index(op.f("ix_verification_requests_status"), table_name="verification_requests")
    op.drop_index(op.f("ix_verification_requests_id"), table_name="verification_requests")
    op.drop_table("verification_requests")
    op.drop_index(op.f("ix_support_tickets_user_id"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_status"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_id"), table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_index(op.f("ix_stakeholders_id"), table_name="stakeholders")
    op.drop_index(op.f("ix_stakeholders_estate_id"), table_name="stakeholders")
    op.drop_table("stakeholders")
    op.drop_index(op.f("ix_panic_alerts_user_id"), table_name="panic_alerts")
    op.drop_index(op.f("ix_panic_alerts_status"), table_name="panic_alerts")
    op.drop_index(op.f("ix_panic_alerts_reason"), table_name="panic_alerts")
    op.drop_index(op.f("ix_panic_alerts_id"), table_name="panic_alerts")
    op.drop_table("panic_alerts")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_member_permissions_user_id"), table_name="member_permissions")
    op.drop_index(op.f("ix_member_permissions_id"), table_name="member_permissions")
    op.drop_table("member_permissions")
    op.drop_index(op.f("ix_invoices_user_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_house_entities_id"), table_name="house_entities")
    op.drop_index(op.f("ix_house_entities_house_number"), table_name="house_entities")
    op.drop_index(op.f("ix_house_entities_formatted_address"), table_name="house_entities")
    op.drop_index(op.f("ix_house_entities_estate_id"), table_name="house_entities")
    op.drop_table("house_entities")
    op.drop_index(op.f("ix_expenses_status"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_channel"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_bills_user_id"), table_name="bills")
    op.drop_index(op.f("ix_bills_status"), table_name="bills")
    op.drop_index(op.f("ix_bills_source_id"), table_name="bills")
    op.drop_index(op.f("ix_bills_is_platform_bill"), table_name="bills")
    op.drop_index(op.f("ix_bills_id"), table_name="bills")
    op.drop_table("bills")
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_target_type"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_target_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_activity_type"), table_name="activity_logs")
    op.drop_index("idx_actlog_user_created", table_name="activity_logs")
    op.drop_index("idx_actlog_type_created", table_name="activity_logs")
    op.drop_index("idx_actlog_target", table_name="activity_logs")
    op.drop_index("idx_actlog_severity", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_users_vouch_code"), table_name="users")
    op.drop_index(op.f("ix_users_verification_tier"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_resident_id"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_house_number"), table_name="users")
    op.drop_index(op.f("ix_users_estate_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_platform_audit_log_id"), table_name="platform_audit_log")
    op.drop_index(op.f("ix_platform_audit_log_estate_id"), table_name="platform_audit_log")
    op.drop_index(op.f("ix_platform_audit_log_actor_id"), table_name="platform_audit_log")
    op.drop_table("platform_audit_log")
    op.drop_index(op.f("ix_firm_admins_id"), table_name="firm_admins")
    op.drop_index(op.f("ix_firm_admins_firm_id"), table_name="firm_admins")
    op.drop_index(op.f("ix_firm_admins_email"), table_name="firm_admins")
    op.drop_index(op.f("ix_firm_admins_designated_estate_id"), table_name="firm_admins")
    op.drop_table("firm_admins")
    op.drop_index(op.f("ix_estates_status"), table_name="estates")
    op.drop_index(op.f("ix_estates_id"), table_name="estates")
    op.drop_index(op.f("ix_estates_estate_code"), table_name="estates")
    op.drop_table("estates")
    op.drop_index(op.f("ix_system_health_checks_overall_status"), table_name="system_health_checks")
    op.drop_index(op.f("ix_system_health_checks_id"), table_name="system_health_checks")
    op.drop_index(op.f("ix_system_health_checks_has_incident"), table_name="system_health_checks")
    op.drop_index("idx_health_incident_created", table_name="system_health_checks")
    op.drop_table("system_health_checks")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_entity_type"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_entity_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_current_cycle_bill_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_status_history_id"), table_name="status_history")
    op.drop_index(op.f("ix_status_history_entity_type"), table_name="status_history")
    op.drop_index(op.f("ix_status_history_entity_id"), table_name="status_history")
    op.drop_table("status_history")
    op.drop_index(op.f("ix_staff_phone_number"), table_name="staff")
    op.drop_index(op.f("ix_staff_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_residents_phone_number"), table_name="residents")
    op.drop_index(op.f("ix_residents_id"), table_name="residents")
    op.drop_index(op.f("ix_residents_house_number"), table_name="residents")
    op.drop_table("residents")
    op.drop_index(op.f("ix_platform_users_id"), table_name="platform_users")
    op.drop_index(op.f("ix_platform_users_email"), table_name="platform_users")
    op.drop_table("platform_users")
    op.drop_index(op.f("ix_payment_ledger_paystack_reference"), table_name="payment_ledger")
    op.drop_index(op.f("ix_payment_ledger_id"), table_name="payment_ledger")
    op.drop_index(op.f("ix_payment_ledger_estate_id"), table_name="payment_ledger")
    op.drop_table("payment_ledger")
    op.drop_index(op.f("ix_otps_phone_number"), table_name="otps")
    op.drop_index(op.f("ix_otps_id"), table_name="otps")
    op.drop_table("otps")
    op.drop_index(op.f("ix_firms_id"), table_name="firms")
    op.drop_index(op.f("ix_firms_firm_code"), table_name="firms")
    op.drop_table("firms")
    op.drop_index(
        op.f("ix_estate_structure_templates_template_id"), table_name="estate_structure_templates"
    )
    op.drop_index(op.f("ix_estate_structure_templates_id"), table_name="estate_structure_templates")
    op.drop_index(
        op.f("ix_estate_structure_templates_category"), table_name="estate_structure_templates"
    )
    op.drop_table("estate_structure_templates")
    # ### end Alembic commands ###
