"""add_structure_provenance_columns

Revision ID: c40c531e4044
Revises: a015e0a72188
Create Date: 2026-08-30 16:24:11.077915

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c40c531e4044"
down_revision: str | None = "a015e0a72188"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "estate_structure_templates",
        sa.Column(
            "structure",
            sa.String(length=300),
            nullable=True,
            comment="Plain-word label of the level sequence, e.g. 'Phase, Street, House Number'",
        ),
    )
    op.add_column(
        "estate_structure_templates",
        sa.Column(
            "example_address",
            sa.String(length=500),
            nullable=True,
            comment="Illustrative full address string showing what this template produces",
        ),
    )
    op.add_column(
        "estate_structure_templates",
        sa.Column(
            "verified",
            sa.Boolean(),
            nullable=True,
            comment="True if modeled on a documented real-world estate's actual address scheme",
        ),
    )
    op.add_column(
        "estate_structure_templates",
        sa.Column(
            "source",
            sa.Text(),
            nullable=True,
            comment="Where the pattern comes from: a named real estate, or a rationale",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("estate_structure_templates", "source")
    op.drop_column("estate_structure_templates", "verified")
    op.drop_column("estate_structure_templates", "example_address")
    op.drop_column("estate_structure_templates", "structure")
    # ### end Alembic commands ###
