/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRegistrationRouteImport } from './routes/(auth)/registration'
import { Route as authRegistrationCriteriaRouteImport } from './routes/(auth)/registration-criteria'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as publicHomeRouteImport } from './routes/(public)/home'
import { Route as AppAccountRecoveryRouteImport } from './routes/_app/account-recovery'
import { Route as AppContactSupportRouteImport } from './routes/_app/contact-support'
import { Route as AppJoinRouteImport } from './routes/_app/join'
import { Route as AppReportIssueRouteImport } from './routes/_app/report-issue'
import { Route as AppResetPinRouteImport } from './routes/_app/reset-pin'
import { Route as AppSignInRouteImport } from './routes/_app/sign-in'
import { Route as AppSplashRouteImport } from './routes/_app/splash'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppVerifyEmailRouteImport } from './routes/_app/verify-email'
import { Route as AppVerifyPhoneRouteImport } from './routes/_app/verify-phone'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppWelcomeBackRouteImport } from './routes/_app/welcome-back'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegistrationRoute = authRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegistrationCriteriaRoute =
  authRegistrationCriteriaRouteImport.update({
    id: '/registration-criteria',
    path: '/registration-criteria',
    getParentRoute: () => authRouteRoute,
  } as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicHomeRoute = publicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => publicRouteRoute,
} as any)
const AppAccountRecoveryRoute = AppAccountRecoveryRouteImport.update({
  id: '/account-recovery',
  path: '/account-recovery',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactSupportRoute = AppContactSupportRouteImport.update({
  id: '/contact-support',
  path: '/contact-support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportIssueRoute = AppReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResetPinRoute = AppResetPinRouteImport.update({
  id: '/reset-pin',
  path: '/reset-pin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignInRoute = AppSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSplashRoute = AppSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVerifyEmailRoute = AppVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVerifyPhoneRoute = AppVerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWelcomeBackRoute = AppWelcomeBackRouteImport.update({
  id: '/welcome-back',
  path: '/welcome-back',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/registration': typeof authRegistrationRoute
  '/registration-criteria': typeof authRegistrationCriteriaRoute
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/account-recovery': typeof AppAccountRecoveryRoute
  '/contact-support': typeof AppContactSupportRoute
  '/join': typeof AppJoinRoute
  '/report-issue': typeof AppReportIssueRoute
  '/reset-pin': typeof AppResetPinRoute
  '/sign-in': typeof AppSignInRoute
  '/splash': typeof AppSplashRoute
  '/support': typeof AppSupportRoute
  '/verify-email': typeof AppVerifyEmailRoute
  '/verify-phone': typeof AppVerifyPhoneRoute
  '/welcome': typeof AppWelcomeRoute
  '/welcome-back': typeof AppWelcomeBackRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/registration': typeof authRegistrationRoute
  '/registration-criteria': typeof authRegistrationCriteriaRoute
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/account-recovery': typeof AppAccountRecoveryRoute
  '/contact-support': typeof AppContactSupportRoute
  '/join': typeof AppJoinRoute
  '/report-issue': typeof AppReportIssueRoute
  '/reset-pin': typeof AppResetPinRoute
  '/sign-in': typeof AppSignInRoute
  '/splash': typeof AppSplashRoute
  '/support': typeof AppSupportRoute
  '/verify-email': typeof AppVerifyEmailRoute
  '/verify-phone': typeof AppVerifyPhoneRoute
  '/welcome': typeof AppWelcomeRoute
  '/welcome-back': typeof AppWelcomeBackRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/registration': typeof authRegistrationRoute
  '/(auth)/registration-criteria': typeof authRegistrationCriteriaRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/home': typeof publicHomeRoute
  '/_app/account-recovery': typeof AppAccountRecoveryRoute
  '/_app/contact-support': typeof AppContactSupportRoute
  '/_app/join': typeof AppJoinRoute
  '/_app/report-issue': typeof AppReportIssueRoute
  '/_app/reset-pin': typeof AppResetPinRoute
  '/_app/sign-in': typeof AppSignInRoute
  '/_app/splash': typeof AppSplashRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/verify-email': typeof AppVerifyEmailRoute
  '/_app/verify-phone': typeof AppVerifyPhoneRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/welcome-back': typeof AppWelcomeBackRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registration'
    | '/registration-criteria'
    | '/about'
    | '/home'
    | '/account-recovery'
    | '/contact-support'
    | '/join'
    | '/report-issue'
    | '/reset-pin'
    | '/sign-in'
    | '/splash'
    | '/support'
    | '/verify-email'
    | '/verify-phone'
    | '/welcome'
    | '/welcome-back'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registration'
    | '/registration-criteria'
    | '/about'
    | '/home'
    | '/account-recovery'
    | '/contact-support'
    | '/join'
    | '/report-issue'
    | '/reset-pin'
    | '/sign-in'
    | '/splash'
    | '/support'
    | '/verify-email'
    | '/verify-phone'
    | '/welcome'
    | '/welcome-back'
    | '/profile'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/_app'
    | '/_authenticated'
    | '/(auth)/registration'
    | '/(auth)/registration-criteria'
    | '/(public)/about'
    | '/(public)/home'
    | '/_app/account-recovery'
    | '/_app/contact-support'
    | '/_app/join'
    | '/_app/report-issue'
    | '/_app/reset-pin'
    | '/_app/sign-in'
    | '/_app/splash'
    | '/_app/support'
    | '/_app/verify-email'
    | '/_app/verify-phone'
    | '/_app/welcome'
    | '/_app/welcome-back'
    | '/_authenticated/profile'
    | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/registration': {
      id: '/(auth)/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof authRegistrationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/registration-criteria': {
      id: '/(auth)/registration-criteria'
      path: '/registration-criteria'
      fullPath: '/registration-criteria'
      preLoaderRoute: typeof authRegistrationCriteriaRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/home': {
      id: '/(public)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicHomeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_app/account-recovery': {
      id: '/_app/account-recovery'
      path: '/account-recovery'
      fullPath: '/account-recovery'
      preLoaderRoute: typeof AppAccountRecoveryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact-support': {
      id: '/_app/contact-support'
      path: '/contact-support'
      fullPath: '/contact-support'
      preLoaderRoute: typeof AppContactSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/join': {
      id: '/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/report-issue': {
      id: '/_app/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof AppReportIssueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reset-pin': {
      id: '/_app/reset-pin'
      path: '/reset-pin'
      fullPath: '/reset-pin'
      preLoaderRoute: typeof AppResetPinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sign-in': {
      id: '/_app/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppSignInRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/splash': {
      id: '/_app/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof AppSplashRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/verify-email': {
      id: '/_app/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AppVerifyEmailRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/verify-phone': {
      id: '/_app/verify-phone'
      path: '/verify-phone'
      fullPath: '/verify-phone'
      preLoaderRoute: typeof AppVerifyPhoneRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/welcome-back': {
      id: '/_app/welcome-back'
      path: '/welcome-back'
      fullPath: '/welcome-back'
      preLoaderRoute: typeof AppWelcomeBackRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authRegistrationRoute: typeof authRegistrationRoute
  authRegistrationCriteriaRoute: typeof authRegistrationCriteriaRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authRegistrationRoute: authRegistrationRoute,
  authRegistrationCriteriaRoute: authRegistrationCriteriaRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicHomeRoute: typeof publicHomeRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicHomeRoute: publicHomeRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAccountRecoveryRoute: typeof AppAccountRecoveryRoute
  AppContactSupportRoute: typeof AppContactSupportRoute
  AppJoinRoute: typeof AppJoinRoute
  AppReportIssueRoute: typeof AppReportIssueRoute
  AppResetPinRoute: typeof AppResetPinRoute
  AppSignInRoute: typeof AppSignInRoute
  AppSplashRoute: typeof AppSplashRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVerifyEmailRoute: typeof AppVerifyEmailRoute
  AppVerifyPhoneRoute: typeof AppVerifyPhoneRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppWelcomeBackRoute: typeof AppWelcomeBackRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRecoveryRoute: AppAccountRecoveryRoute,
  AppContactSupportRoute: AppContactSupportRoute,
  AppJoinRoute: AppJoinRoute,
  AppReportIssueRoute: AppReportIssueRoute,
  AppResetPinRoute: AppResetPinRoute,
  AppSignInRoute: AppSignInRoute,
  AppSplashRoute: AppSplashRoute,
  AppSupportRoute: AppSupportRoute,
  AppVerifyEmailRoute: AppVerifyEmailRoute,
  AppVerifyPhoneRoute: AppVerifyPhoneRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppWelcomeBackRoute: AppWelcomeBackRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
