/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as authAdminLoginRouteImport } from './routes/(auth)/admin-login'
import { Route as authRegistrationRouteImport } from './routes/(auth)/registration'
import { Route as authRegistrationCriteriaRouteImport } from './routes/(auth)/registration-criteria'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as publicHomeRouteImport } from './routes/(public)/home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppJoinRouteImport } from './routes/app/join'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppSplashRouteImport } from './routes/app/splash'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppVouchRouteImport } from './routes/app/vouch'
import { Route as AppWelcomeRouteImport } from './routes/app/welcome'
import { Route as AppOnboardingGetStartedFindEstateIdRouteImport } from './routes/app/onboarding/get-started/find-estate-id'
import { Route as AppOnboardingGetStartedNoEstateIdRouteImport } from './routes/app/onboarding/get-started/no-estate-id'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const authAdminLoginRoute = authAdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegistrationRoute = authRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegistrationCriteriaRoute = authRegistrationCriteriaRouteImport.update({
  id: '/registration-criteria',
  path: '/registration-criteria',
  getParentRoute: () => authRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicHomeRoute = publicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSplashRoute = AppSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVouchRoute = AppVouchRouteImport.update({
  id: '/vouch',
  path: '/vouch',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingGetStartedFindEstateIdRoute =
  AppOnboardingGetStartedFindEstateIdRouteImport.update({
    id: '/onboarding/get-started/find-estate-id',
    path: '/onboarding/get-started/find-estate-id',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOnboardingGetStartedNoEstateIdRoute = AppOnboardingGetStartedNoEstateIdRouteImport.update({
  id: '/onboarding/get-started/no-estate-id',
  path: '/onboarding/get-started/no-estate-id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/admin-login': typeof authAdminLoginRoute
  '/registration': typeof authRegistrationRoute
  '/registration-criteria': typeof authRegistrationCriteriaRoute
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app/join': typeof AppJoinRoute
  '/app/login': typeof AppLoginRoute
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/vouch': typeof AppVouchRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/onboarding/get-started/find-estate-id': typeof AppOnboardingGetStartedFindEstateIdRoute
  '/app/onboarding/get-started/no-estate-id': typeof AppOnboardingGetStartedNoEstateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/admin-login': typeof authAdminLoginRoute
  '/registration': typeof authRegistrationRoute
  '/registration-criteria': typeof authRegistrationCriteriaRoute
  '/about': typeof publicAboutRoute
  '/home': typeof publicHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app/join': typeof AppJoinRoute
  '/app/login': typeof AppLoginRoute
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/vouch': typeof AppVouchRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/onboarding/get-started/find-estate-id': typeof AppOnboardingGetStartedFindEstateIdRoute
  '/app/onboarding/get-started/no-estate-id': typeof AppOnboardingGetStartedNoEstateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/admin-login': typeof authAdminLoginRoute
  '/(auth)/registration': typeof authRegistrationRoute
  '/(auth)/registration-criteria': typeof authRegistrationCriteriaRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/home': typeof publicHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/app/join': typeof AppJoinRoute
  '/app/login': typeof AppLoginRoute
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/vouch': typeof AppVouchRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/(public)/': typeof publicIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/onboarding/get-started/find-estate-id': typeof AppOnboardingGetStartedFindEstateIdRoute
  '/app/onboarding/get-started/no-estate-id': typeof AppOnboardingGetStartedNoEstateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/admin-login'
    | '/registration'
    | '/registration-criteria'
    | '/about'
    | '/home'
    | '/profile'
    | '/app/join'
    | '/app/login'
    | '/app/splash'
    | '/app/support'
    | '/app/vouch'
    | '/app/welcome'
    | '/app/'
    | '/app/onboarding/get-started/find-estate-id'
    | '/app/onboarding/get-started/no-estate-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/registration'
    | '/registration-criteria'
    | '/about'
    | '/home'
    | '/profile'
    | '/app/join'
    | '/app/login'
    | '/app/splash'
    | '/app/support'
    | '/app/vouch'
    | '/app/welcome'
    | '/app'
    | '/app/onboarding/get-started/find-estate-id'
    | '/app/onboarding/get-started/no-estate-id'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/_authenticated'
    | '/app'
    | '/(auth)/admin-login'
    | '/(auth)/registration'
    | '/(auth)/registration-criteria'
    | '/(public)/about'
    | '/(public)/home'
    | '/_authenticated/profile'
    | '/app/join'
    | '/app/login'
    | '/app/splash'
    | '/app/support'
    | '/app/vouch'
    | '/app/welcome'
    | '/(public)/'
    | '/app/'
    | '/app/onboarding/get-started/find-estate-id'
    | '/app/onboarding/get-started/no-estate-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/admin-login': {
      id: '/(auth)/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof authAdminLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/registration': {
      id: '/(auth)/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof authRegistrationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/registration-criteria': {
      id: '/(auth)/registration-criteria'
      path: '/registration-criteria'
      fullPath: '/registration-criteria'
      preLoaderRoute: typeof authRegistrationCriteriaRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/home': {
      id: '/(public)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicHomeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/join': {
      id: '/app/join'
      path: '/join'
      fullPath: '/app/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/splash': {
      id: '/app/splash'
      path: '/splash'
      fullPath: '/app/splash'
      preLoaderRoute: typeof AppSplashRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vouch': {
      id: '/app/vouch'
      path: '/vouch'
      fullPath: '/app/vouch'
      preLoaderRoute: typeof AppVouchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding/get-started/find-estate-id': {
      id: '/app/onboarding/get-started/find-estate-id'
      path: '/onboarding/get-started/find-estate-id'
      fullPath: '/app/onboarding/get-started/find-estate-id'
      preLoaderRoute: typeof AppOnboardingGetStartedFindEstateIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding/get-started/no-estate-id': {
      id: '/app/onboarding/get-started/no-estate-id'
      path: '/onboarding/get-started/no-estate-id'
      fullPath: '/app/onboarding/get-started/no-estate-id'
      preLoaderRoute: typeof AppOnboardingGetStartedNoEstateIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAdminLoginRoute: typeof authAdminLoginRoute
  authRegistrationRoute: typeof authRegistrationRoute
  authRegistrationCriteriaRoute: typeof authRegistrationCriteriaRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAdminLoginRoute: authAdminLoginRoute,
  authRegistrationRoute: authRegistrationRoute,
  authRegistrationCriteriaRoute: authRegistrationCriteriaRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(authRouteRouteChildren)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicHomeRoute: typeof publicHomeRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicHomeRoute: publicHomeRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(publicRouteRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(
  AuthenticatedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppJoinRoute: typeof AppJoinRoute
  AppLoginRoute: typeof AppLoginRoute
  AppSplashRoute: typeof AppSplashRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVouchRoute: typeof AppVouchRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOnboardingGetStartedFindEstateIdRoute: typeof AppOnboardingGetStartedFindEstateIdRoute
  AppOnboardingGetStartedNoEstateIdRoute: typeof AppOnboardingGetStartedNoEstateIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppJoinRoute: AppJoinRoute,
  AppLoginRoute: AppLoginRoute,
  AppSplashRoute: AppSplashRoute,
  AppSupportRoute: AppSupportRoute,
  AppVouchRoute: AppVouchRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppOnboardingGetStartedFindEstateIdRoute: AppOnboardingGetStartedFindEstateIdRoute,
  AppOnboardingGetStartedNoEstateIdRoute: AppOnboardingGetStartedNoEstateIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
