"""Visitor code model — tenant schema.

V2 update: Synced with estate_management_BE fields that the Figma flow requires:
- visitor_image (facial capture at gate)
- time_of_visit / estimated_departure (scheduling)
- actual_arrival / actual_departure (gate check-in/out)
- reason_for_visit
- phone_number (V1 compatibility)

Reference: Figma "Home → Vouching" and "Enter resident vouche code"
"""

from sqlalchemy import Column, String, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship

from api.v1.models.base_model import BaseTableModel


class VisitorCode(BaseTableModel):
    """Visitor access codes generated by residents — tenant schema."""

    __tablename__ = "visitor_codes"

    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    # ── Visitor Info ──
    visitor_name = Column(String(100), nullable=False)
    phone_number = Column(String(20), nullable=True)  # V1 compat: was visitor_phone
    visitor_image = Column(String(500), nullable=True)  # V2: facial capture / photo URL

    # ── Code ──
    code = Column(String(20), unique=True, nullable=False, index=True)

    # ── Scheduling (from V1 — required by Figma visitor flow) ──
    time_of_visit = Column(DateTime(timezone=True), nullable=True)
    estimated_departure = Column(DateTime(timezone=True), nullable=True)
    reason_for_visit = Column(Text, nullable=True)

    # ── Gate Check-in/out (from V1 — security dashboard needs these) ──
    actual_arrival = Column(DateTime(timezone=True), nullable=True)
    actual_departure = Column(DateTime(timezone=True), nullable=True)

    # ── Status ──
    is_used = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)

    # Relationships
    user = relationship("User", back_populates="visitor_codes")
    visits = relationship("Visitor", back_populates="visitor_code", cascade="all, delete-orphan")
