"""Standard response message constants."""

EMAIL_IN_USE = "This email is already in use."
PHONE_IN_USE = "This phone number is already registered."
NOT_FOUND = "Not found!"
ID_OR_UNIQUE_ID_REQUIRED = "ID or Unique ID required!"
INVALID_CREDENTIALS = "Invalid Credentials!"
COULD_NOT_VALIDATE_CRED = "Could not validate credentials."
SUCCESS = "SUCCESS"
EXPIRED = "Token expired."
ACCOUNT_LOCKED = "Account temporarily locked due to too many failed attempts."
INVALID_PIN = "Invalid PIN."
INVALID_OTP = "Invalid or expired OTP."
OTP_EXPIRED = "OTP has expired. Please request a new one."
OTP_MAX_RETRIES = "Maximum OTP attempts reached. Please request a new OTP."
PIN_BLOCKED_PATTERN = "This PIN is too simple. Please choose a different PIN."
ESTATE_NOT_FOUND = "Estate not found. Please check your estate code."
UNAUTHORIZED = "You do not have permission to perform this action."
SUBSCRIPTION_EXPIRED = "Your estate's subscription has expired."
