// ──────────────────────────────────────────────────────────
// Estate types — mirrors BE estate model + estate_id.py
//
// Used by: rezzident_FE, rezzident_MB, packages/api-client
// Source of truth: apps/rezzident_BE/api/v1/models/estate.py
//                  apps/rezzident_BE/api/v1/schemas/estate.py
// ──────────────────────────────────────────────────────────

// ── Enums ──

export type EstateStatus = "pending" | "active" | "suspended" | "deleted";

export type OnboardingStep =
  | "registration"
  | "stakeholder_verification"
  | "house_setup"
  | "active";

export type ManagementType = "community" | "firm";

// ── Core Estate ──

export interface Estate {
  id: string;
  estate_code: string; // e.g., "PAR-7X3KM" — generated by system
  schema_name: string; // e.g., "est_par7x3km" — PostgreSQL tenant schema
  name: string;
  address: string;
  city: string | null;
  state: string | null;
  management_type: ManagementType;
  status: EstateStatus;
  onboarding_step: OnboardingStep;
  has_structure: boolean;
  created_at?: string;
}

// ── Structure Template ──

export interface StructureLevel {
  level: number;
  label: string; // e.g., "Block", "Floor", "Flat"
  type: "text" | "numeric" | "alphanumeric" | "select";
  required: boolean;
  options?: string[]; // For 'select' type
}

export interface EstateStructureTemplate {
  template_id: string;
  name: string;
  description?: string;
  category?: string;
  levels: StructureLevel[];
  address_format?: string; // e.g., "{Block}, Floor {Floor}, Flat {Flat}"
}

// ── Stakeholder ──

export interface StakeholderPayload {
  full_name: string;
  phone_number: string;
  email?: string;
  role_title?: "chairman" | "secretary" | "treasurer" | "stakeholder" | "firm_rep";
  is_primary?: boolean;
}

// ── Registration Request (POST /api/v1/estates/register) ──

export interface EstateRegistrationPayload {
  name: string;
  address: string;
  city?: string;
  state?: string;
  management_type?: ManagementType;
  structure_template_id?: string;
  custom_structure?: StructureLevel[];
  stakeholders?: StakeholderPayload[];
  house_count_tier?: "<10" | "<20" | "<50" | "<100" | "100+";
}

// ── Lookup Request (GET /api/v1/estates/lookup/{code}) ──

export interface EstateJoinPayload {
  estate_code: string; // resident enters this to join an estate
}

// ── Response Data Shapes ──

export interface EstateRegistrationResponse {
  id: string;
  estate_code: string;
  schema_name: string;
  name: string;
  address: string;
  city: string | null;
  state: string | null;
  management_type: ManagementType;
  status: EstateStatus;
  onboarding_step: OnboardingStep;
}

export interface EstateLookupResponse {
  id: string;
  estate_code: string;
  name: string;
  city: string | null;
  state: string | null;
  has_structure: boolean;
}
